# General Configuration
[general]
# Directory containing source files
src_dir = "data/intermediate/animes"
# Directory to save output files
dst_dir = "data"
# Extra path component to add between dst_dir/[training|intermediate] and image type
extra_path_component = ""
# Stage number or alias to start from
start_stage = 1
# Stage number or alias to end at
end_stage = 7
# Directory to save logs. Set to None or none to disable.
log_dir = "logs"
# Prefix for log files
log_prefix = "logfile"
# Pipeline type that is used to construct dataset
pipeline_type = "screenshots"
# Image type that we are dealing with, used for folder name and might appear in caption as well. Default to pipeline_type.
image_type = "screenshots"

# Video Extraction Configuration
[video_extraction]
# Only extract key frames
extract_key = true
# Output image prefix
image_prefix = "my_favorite_anime"
# Episode number to start with
ep_init = 1

# Character Cropping Configuration
[character_cropping]
# Use 3 stage crop to get halfbody and head crops
# Set to {} or comment it to disable
use_3stage_crop = {}

# Character Clustering/Classification Configuration
[character_classification]
# Directory containing reference character images
character_ref_dir = "path/to/reference/character/images"
# The number of additional reference images to add to each character from classification result"
n_add_to_ref_per_character = 0
# Whether to keep unnamed clusters when reference images are provided or when characters are available in metadata
keep_unnamed_clusters = true

# Dataset Construction Configuration
[dataset_construction]
# Number of images with no characters to keep
n_anime_reg = 500

# Tagging Configuration
[tagging]
# Whether to overwrite existing tags
overwrite_tags = false

# General Tag Processing Configuration
[tag_processing]
# Mode to sort the tags
sort_mode = "score"
# Max number of tags to include in caption
max_tag_number = 30
# Process tags from original tags instead of processed tags
process_from_original_tags = true
# Different ways to prune tags
pruned_mode = "character_core"

# Core Tag Processing Configuration
[core_tag_processing]
# Minimum frequency for a tag to be considered a core tag
core_frequency_thresh = 0.4
# The difficulty level up to which tags should be dropped
drop_difficulty = 2
# Whether to drop all core tags or not
drop_all_core = false
# The difficulty level from which tags should be used for embedding initialization
emb_min_difficulty = 1
# The difficulty level up to which tags should be used for embedding initialization
emb_max_difficulty = 2
# Whether to use all core tags for embedding initialization
emb_init_all_core = false

# Captioning Configuration
[captioning]
# For separating items of a single field of caption
caption_inner_sep = ", "
# For separating different fields of caption
caption_outer_sep = ", "
# For separating characters
character_sep = ", "
# For separating items of a single field of character
character_inner_sep = " "
# For separating different fields of character
character_outer_sep = ", "
# Probability to include number of people in captions
use_npeople_prob = 0
# Probability to include character info in captions
use_character_prob = 1
# Probability to include copyright info in captions
use_copyright_prob = 0
# Probability to include image type info in captions
use_image_type_prob = 1
# Probability to include artist info in captions
use_artist_prob = 0
# Probability to include rating info in captions
use_rating_prob = 1
# Probability to include tag info in captions
use_tags_prob = 1

# Folder Organization Configuration
[folder_organization]
# Description of the concept balancing directory hierarchy
arrange_format = "n_characters/character"
# If have more than X characters put X+
max_character_number = 3
# Put others instead of character name if number of images of the character combination is smaller than this number
min_images_per_combination = 10

# Balancing Configuration
[balancing]
# Minimum multiply of each image
min_multiply = 1
# Maximum multiply of each image
max_multiply = 100
# If provided use the provided csv to modify weights
weight_csv = "configs/csv_examples/default_weighting.csv"
