# General Configuration
[general]
# Directory containing source files
src_dir = "data/intermediate/screenshots/raw"
# Directory to save output files
dst_dir = "data"
# Extra path component to add between dst_dir/[training|intermediate] and image type
extra_path_component = ""
# Stage number or alias to start from
start_stage = 0
# Stage number or alias to end at
end_stage = 7
# Directory to save logs. Set to None or none to disable.
log_dir = "logs"
# Prefix for log files, defaults to --anime_name if provided otherwise 'logfile'
log_prefix = {}
# Pipeline type that is used to construct dataset
pipeline_type = "screenshots"
# Image type that we are dealing with, used for folder name and might appear in caption as well. Default to --pipeline_type.
image_type = "screenshots"

# Configuration for downloading animes from nyaa.si
[nyaa_download]
# The anime name used for downloading animes from nyaa.si
anime_name = "my_favorite_anime"
# The candidate submitters used for downloading animes from nyaa.si
candidate_submitters = ["Erai-raws", "SubsPlease", "CameEsp", "ohys"]
# The resolution of anime to download
anime_resolution = 720
# The minimum episode to download
# Set to {} or comment this line to disable
min_download_episode = {}
# The maximum episode to download
# Set to {} or comment this line to disable
max_download_episode = {}

# Video Extraction Configuration
[video_extraction]
# Only extract key frames
extract_key = true
# Output image prefix, when not provided we try to infer it from video file name
image_prefix = {}
# Episode number to start with, when not provided we try to infer it from video file name
ep_init = {}

# Character Cropping Configuration
[character_cropping]
# Use 3 stage crop to get halfbody and head crops
# Set to {} or comment this line to disable
use_3stage_crop = {}

# Character Clustering/Classification Configuration
[character_classification]
# Directory containing reference character images
character_ref_dir = "data/ref_images"
# The number of additional reference images to add to each character from classification result"
n_add_to_ref_per_character = 0
# Whether to keep unnamed clusters when reference images are provided or when characters are available in metadata
keep_unnamed_clusters = false

# Dataset Construction Configuration
[dataset_construction]
# Number of images with no characters to keep
n_anime_reg = 500

# Tagging Configuration
[tagging]
# Whether to overwrite existing tags
overwrite_tags = false

# General Tag Processing Configuration
[tag_processing]
# Mode to sort the tags
sort_mode = "score"
# Whether to append dropped character tags to the caption
append_dropped_character_tags = false
# Max number of tags to include in caption
max_tag_number = 30
# Process tags from original tags instead of processed tags
process_from_original_tags = true
# Different ways to prune tags
prune_mode = "character_core"

# Folder Organization Configuration
[folder_organization]
# Description of the concept balancing directory hierarchy
arrange_format = "n_characters/character"
# If have more than X characters put X+
max_character_number = 3
# Put others instead of character name if number of images of the character combination is smaller than this number
min_images_per_combination = 10

# Balancing Configuration
[balancing]
# Minimum multiply of each image
min_multiply = 1
# Maximum multiply of each image
max_multiply = 100
# If provided use the provided csv to modify weights
weight_csv = "configs/csv_examples/default_weighting.csv"
